### ISSUE TITLE
[Your Phone Prefix] [Your Phone Number] entered into mobile phone number field when script selects easy apply 

### ISSUE THREAD

**Issue by RJamieKelly** [feder-cr/linkedIn_auto_jobs_applier_with_AI#110]
my phone details are correct and i've double checked the example file.

`Starting the application process for this page...
Traceback (most recent call last):
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 63, in job_apply
    self._fill_application_form(job)
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 130, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 145, in _next_or_submit
    self._check_for_errors()
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 158, in _check_for_errors
    raise Exception(f"Failed answering or file upload. {str([e.text for e in error_elements])}")
Exception: Failed answering or file upload. ['Enter a valid phone number']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_job_manager.py", line 138, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 67, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception: 
Traceback:
Traceback (most recent call last):
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 63, in job_apply
    self._fill_application_form(job)
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 130, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 145, in _next_or_submit
    self._check_for_errors()
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 158, in _check_for_errors
    raise Exception(f"Failed answering or file upload. {str([e.text for e in error_elements])}")
Exception: Failed answering or file upload. ['Enter a valid phone number']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_job_manager.py", line 138, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 67, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception: 
Traceback:
Traceback (most recent call last):
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 63, in job_apply
    self._fill_application_form(job)
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 130, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 145, in _next_or_submit
    self._check_for_errors()
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 158, in _check_for_errors
    raise Exception(f"Failed answering or file upload. {str([e.text for e in error_elements])}")
Exception: Failed answering or file upload. ['Enter a valid phone number']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_job_manager.py", line 138, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 67, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception: 
Traceback:
Traceback (most recent call last):
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 63, in job_apply
    self._fill_application_form(job)
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 130, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 145, in _next_or_submit
    self._check_for_errors()
  File "/Users/ser/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 158, in _check_for_errors
    raise Exception(f"Failed answering or file upload. {str([e.text for e in error_elements])}")
Exception: Failed answering or file upload. ['Enter a valid phone number']
`

**Comment by waleedbkhalid** [comment]
same issue

**Comment by feder-cr** [comment]
@RJamieKelly @waleedbkhalid any update?
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
