### ISSUE TITLE
Getting selector errors

### ISSUE THREAD

**Issue by safakhan413** [feder-cr/linkedIn_auto_jobs_applier_with_AI#123]
Traceback (most recent call last):
  File "d:\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 63, in job_apply
    self._fill_application_form(job)
  File "d:\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 129, in _fill_application_form
    self.fill_up(job)
  File "d:\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 170, in fill_up
    easy_apply_content = self.driver.find_element(By.CLASS_NAME, 'jobs-easy-apply-content')
  File "C:\Users\cleopatra\anaconda3\envs\hawk\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\cleopatra\anaconda3\envs\hawk\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\cleopatra\anaconda3\envs\hawk\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-easy-apply-content"}
  (Session info: chrome=128.0.6613.85)
Stacktrace:
        GetHandleVerifier [0x00EF8283+26163]
        (No symbol) [0x00E89D34]
        (No symbol) [0x00D824C3]
        (No symbol) [0x00DC7453]
        (No symbol) [0x00DC762B]
        (No symbol) [0x00E06B62]
        (No symbol) [0x00DEAD04]
        (No symbol) [0x00E04661]
        (No symbol) [0x00DEAA56]
        (No symbol) [0x00DBBE89]
        (No symbol) [0x00DBC8CD]
        GetHandleVerifier [0x011CCF73+2994979]
        GetHandleVerifier [0x012217E9+3341209]
        GetHandleVerifier [0x00F87B5F+614159]
        GetHandleVerifier [0x00F8F1EC+644508]
        (No symbol) [0x00E9286D]
        (No symbol) [0x00E8F768]
        (No symbol) [0x00E8F905]
        (No symbol) [0x00E81C86]
        BaseThreadInitThunk [0x76737BA9+25]
        RtlInitializeExceptionChain [0x77A2C11B+107]
        RtlClearBits [0x77A2C09F+191]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_job_manager.py", line 138, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File "d:\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 67, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception:
Traceback:
Traceback (most recent call last):
  File "d:\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 63, in job_apply
    self._fill_application_form(job)
  File "d:\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 129, in _fill_application_form
    self.fill_up(job)
  File "d:\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 170, in fill_up
    easy_apply_content = self.driver.find_element(By.CLASS_NAME, 'jobs-easy-apply-content')
  File "C:\Users\cleopatra\anaconda3\envs\hawk\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 831, in find_element

**Comment by feder-cr** [comment]
restart the bot
@safakhan413 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
