### ISSUE TITLE
ImportError: DLL load failed while importing levenshtein_cpp: The specified module could not be found.

### ISSUE THREAD

**Issue by Rishabsharma112000** [feder-cr/linkedIn_auto_jobs_applier_with_AI#131]
Getting this error after running python main.py- 

E:\LinkedIn_AIHawk_automatic_job_application>python main.py
Traceback (most recent call last):
  File "E:\LinkedIn_AIHawk_automatic_job_application\main.py", line 13, in <module>
    from src.gpt import GPTAnswerer
  File "E:\LinkedIn_AIHawk_automatic_job_application\src\gpt.py", line 14, in <module>
    from Levenshtein import distance
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\Levenshtein\__init__.py", line 35, in <module>
    from Levenshtein.levenshtein_cpp import (
ImportError: DLL load failed while importing levenshtein_cpp: The specified module could not be found.

**Comment by feder-cr** [comment]
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
