### ISSUE TITLE
Generate HTML Failing at Education Section

### ISSUE THREAD

**Issue by acortiv** [feder-cr/linkedIn_auto_jobs_applier_with_AI#176]
Traceback (most recent call last):
  File "C:\Users\tacor\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 63, in job_apply
    self._fill_application_form(job)
  File "C:\Users\tacor\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 129, in _fill_application_form
    self.fill_up(job)
  File "C:\Users\tacor\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 173, in fill_up
    self._process_form_element(element, job)
  File "C:\Users\tacor\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 177, in _process_form_element
    self._handle_upload_fields(element, job)
  File "C:\Users\tacor\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 194, in _handle_upload_fields
    self._create_and_upload_resume(element, job)
  File "C:\Users\tacor\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 210, in _create_and_upload_resume
    raise Exception(f"Upload failed: \nTraceback:\n{tb_str}")
Exception: Upload failed:
Traceback:
Traceback (most recent call last):
  File "C:\Users\tacor\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 204, in _create_and_upload_resume
    f.write(base64.b64decode(self.resume_generator_manager.pdf_base64(job_description_text=job.description)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tacor\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\lib_resume_builder_AIHawk\manager_facade.py", line 78, in pdf_base64
    self.resume_generator.create_resume_job_description_text(style_path, job_description_text, temp_html_path)
  File "C:\Users\tacor\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\lib_resume_builder_AIHawk\resume_generator.py", line 38, in create_resume_job_description_text
    self._create_resume(gpt_answerer, style_path, temp_html_path)
  File "C:\Users\tacor\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\lib_resume_builder_AIHawk\resume_generator.py", line 19, in _create_resume
    message = template.substitute(markdown=gpt_answerer.generate_html_resume(), style_path=style_path)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tacor\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\lib_resume_builder_AIHawk\gpt_resume_job_description.py", line 313, in generate_html_resume
    f"    {results['education']}\n"
           ~~~~~~~^^^^^^^^^^^^^
KeyError: 'education'



Getting this error when it tries to generate and upload the resume.  any ideas on how to debug?

**Comment by acortiv** [comment]
Looks like the autogenerated CV is caching somewhere in the GPT API prompts causing the issue.  This stemmed from me having 2 education sections I believe.  I started a clean env and will report results.
