### ISSUE TITLE
StaleElementReferenceException and NoSuchElementException

### ISSUE THREAD

**Issue by karnoark** [feder-cr/linkedIn_auto_jobs_applier_with_AI#210]
I'm getting the following error, while I’ve observed two issues. In one instance, it’s unable to find the 'See More' button in the job description. In another instance, it starts the application process but closes the easy application form after the resume upload step

Here is the error log:
Traceback (most recent call last):
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 63, in job_apply
    self._fill_application_form(job)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 129, in _fill_application_form
    self.fill_up(job)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 173, in fill_up
    self._process_form_element(element, job)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 177, in _process_form_element
    self._handle_upload_fields(element, job)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 192, in _handle_upload_fields
    element.send_keys(str(self.resume_path.resolve()))
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 231, in send_keys
    self._execute(
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=128.0.6613.114)
Stacktrace:
        GetHandleVerifier [0x00EC8283+26163]
        (No symbol) [0x00E59D34]
        (No symbol) [0x00D524C3]
        (No symbol) [0x00D58064]
        (No symbol) [0x00D59948]
        (No symbol) [0x00D599C0]
        (No symbol) [0x00D97EED]
        (No symbol) [0x00D97F71]
        (No symbol) [0x00D900CE]
        (No symbol) [0x00DBACBC]
        (No symbol) [0x00D8D445]
        (No symbol) [0x00DBAF54]
        (No symbol) [0x00DD4661]
        (No symbol) [0x00DBAA56]
        (No symbol) [0x00D8BE89]
        (No symbol) [0x00D8C8CD]
        GetHandleVerifier [0x0119CF73+2994979]
        GetHandleVerifier [0x011F17E9+3341209]
        GetHandleVerifier [0x00F57B5F+614159]
        GetHandleVerifier [0x00F5F1EC+644508]
        (No symbol) [0x00E6286D]
        (No symbol) [0x00E5F768]
        (No symbol) [0x00E5F905]
        (No symbol) [0x00E51C86]
        BaseThreadInitThunk [0x75FCFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77C980CE+286]
        RtlGetAppContainerNamedObjectPath [0x77C9809E+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_job_manager.py", line 138, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 67, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception:
Traceback:
Traceback (most recent call last):
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 63, in job_apply
    self._fill_application_form(job)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 129, in _fill_application_form
    self.fill_up(job)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 173, in fill_up
    self._process_form_element(element, job)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 177, in _process_form_element
    self._handle_upload_fields(element, job)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 192, in _handle_upload_fields
    element.send_keys(str(self.resume_path.resolve()))
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 231, in send_keys
    self._execute(
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=128.0.6613.114)
Stacktrace:
        GetHandleVerifier [0x00EC8283+26163]
        (No symbol) [0x00E59D34]
        (No symbol) [0x00D524C3]
        (No symbol) [0x00D58064]
        (No symbol) [0x00D59948]
        (No symbol) [0x00D599C0]
        (No symbol) [0x00D97EED]
        (No symbol) [0x00D97F71]
        (No symbol) [0x00D900CE]
        (No symbol) [0x00DBACBC]
        (No symbol) [0x00D8D445]
        (No symbol) [0x00DBAF54]
        (No symbol) [0x00DD4661]
        (No symbol) [0x00DBAA56]
        (No symbol) [0x00D8BE89]
        (No symbol) [0x00D8C8CD]
        GetHandleVerifier [0x0119CF73+2994979]
        GetHandleVerifier [0x011F17E9+3341209]
        GetHandleVerifier [0x00F57B5F+614159]
        GetHandleVerifier [0x00F5F1EC+644508]
        (No symbol) [0x00E6286D]
        (No symbol) [0x00E5F768]
        (No symbol) [0x00E5F905]
        (No symbol) [0x00E51C86]
        BaseThreadInitThunk [0x75FCFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77C980CE+286]
        RtlGetAppContainerNamedObjectPath [0x77C9809E+238]

Traceback (most recent call last):
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 97, in _get_job_description
    see_more_button = self.driver.find_element(By.XPATH, '//button[@aria-label="Click to see more description"]')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "D:\Career\JobSearch\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@aria-label="Click to see more description"]"}
  (Session info: chrome=128.0.6613.114)
Stacktrace:
        GetHandleVerifier [0x00EC8283+26163]
        (No symbol) [0x00E59D34]
        (No symbol) [0x00D524C3]
        (No symbol) [0x00D97453]
        (No symbol) [0x00D9762B]
        (No symbol) [0x00DD6B62]
        (No symbol) [0x00DBAD04]
        (No symbol) [0x00DD4661]
        (No symbol) [0x00DBAA56]
        (No symbol) [0x00D8BE89]
        (No symbol) [0x00D8C8CD]
        GetHandleVerifier [0x0119CF73+2994979]
        GetHandleVerifier [0x011F17E9+3341209]
        GetHandleVerifier [0x00F57B5F+614159]
        GetHandleVerifier [0x00F5F1EC+644508]
        (No symbol) [0x00E6286D]
        (No symbol) [0x00E5F768]
        (No symbol) [0x00E5F905]
        (No symbol) [0x00E51C86]
        BaseThreadInitThunk [0x75FCFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77C980CE+286]
        RtlGetAppContainerNamedObjectPath [0x77C9809E+238]

**Comment by feder-cr** [comment]
@karnoark Is the bot applying?
Or is this a fatal error?
join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by karnoark** [comment]
@feder-cr No it doesn't apply, it moves on to the next job posting and encounter similar situation. in the both the instances  I'm already in the group, I'll post it there.

**Comment by karnoark** [comment]
I no loner face this issue, so closing it.
