### ISSUE TITLE
During handling of the above exception, another exception occurred error

### ISSUE THREAD

**Issue by diegohd8** [feder-cr/linkedIn_auto_jobs_applier_with_AI#244]
Traceback (most recent call last):
  File "\Hawk\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_easy_applier.py", line 57, in job_apply
    easy_apply_button = self._find_easy_apply_button()
  File "\Hawk\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_easy_applier.py", line 73, in _find_easy_apply_button
    buttons = WebDriverWait(self.driver, 10).until(
  File "\linkedIn_auto_jobs_applier_with_AI\virtual\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Hawk\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_job_manager.py", line 138, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File "C:\Users\diego\OneDrive\Escritorio\Hawk\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_easy_applier.py", line 67, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception:
Traceback:
Traceback (most recent call last):
  File "Hawk\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_easy_applier.py", line 57, in job_apply
    easy_apply_button = self._find_easy_apply_button()
  File "Hawk\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_easy_applier.py", line 73, in _find_easy_apply_button
    buttons = WebDriverWait(self.driver, 10).until(
  File "Hawk\linkedIn_auto_jobs_applier_with_AI\virtual\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by queukat** [comment]
fixed in 
https://github.com/queukat/linkedIn_auto_jobs_applier_with_AI/tree/v3
