### ISSUE TITLE
Bot Stops and Exits Application Process When Encountering City, Address, or LinkedIn Profile Fields

### ISSUE THREAD

**Issue by baseadinho** [feder-cr/linkedIn_auto_jobs_applier_with_AI#264]
I'm encountering an issue where the bot fails to proceed correctly when it reaches certain fields during the application process after clicking "Easy Apply."

**City Field/adress**: The bot fills in the city field correctly but then stops and exits the application process, moving on to the next job without completing the current application.

**LinkedIn Profile Field**: When the bot encounters a field for the LinkedIn profile, which is already pre-filled, it doesn't proceed by clicking "Next" or "Submit." Instead, it exits the application process and moves on to the next job.

This behavior results in the bot skipping applications it could potentially complete. It would be helpful if the bot could handle these fields properly, especially since the LinkedIn profile field is typically already filled out.
Traceback (most recent call last):

  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 61, in job_apply
    self._fill_application_form(job)
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 126, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 139, in _next_or_submit
    next_button.click()
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-label="Continue to next step" id="ember326" class="artdeco-button artdeco-button--2 artdeco-button--primary ember-view" data-easy-apply-next-button="" type="button">...</button> is not clickable at point (954, 271). Other element would receive the click: <div class="search-typeahead-v2__hit search-typeahead-v2__hit--autocomplete" data-test-single-typeahead-entity-form-search-result="true">...</div>
  (Session info: chrome=128.0.6613.120)
Stacktrace:
        GetHandleVerifier [0x01078213+26163]
        (No symbol) [0x01009CC4]
        (No symbol) [0x00F024C3]
        (No symbol) [0x00F4D357]
        (No symbol) [0x00F4B759]
        (No symbol) [0x00F4964B]
        (No symbol) [0x00F48C2F]
        (No symbol) [0x00F3D9AF]
        (No symbol) [0x00F6ACBC]
        (No symbol) [0x00F3D445]
        (No symbol) [0x00F6AF54]
        (No symbol) [0x00F84661]
        (No symbol) [0x00F6AA56]
        (No symbol) [0x00F3BE89]
        (No symbol) [0x00F3C8CD]
        GetHandleVerifier [0x0134D313+2996019]
        GetHandleVerifier [0x013A1B89+3342249]
        GetHandleVerifier [0x01107AEF+614159]
        GetHandleVerifier [0x0110F17C+644508]
        (No symbol) [0x010127FD]
        (No symbol) [0x0100F6F8]
        (No symbol) [0x0100F895]
        (No symbol) [0x01001C16]
        BaseThreadInitThunk [0x757AFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x779780CE+286]
        RtlGetAppContainerNamedObjectPath [0x7797809E+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_job_manager.py", line 126, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 65, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception:
Traceback:
Traceback (most recent call last):
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 61, in job_apply
    self._fill_application_form(job)
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 126, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 139, in _next_or_submit
    next_button.click()
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User001\Documents\Python Projects\BotLinkedin\LinkedIn_AIHawk_automatic_job_application\virtual\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-label="Continue to next step" id="ember326" class="artdeco-button artdeco-button--2 artdeco-button--primary ember-view" data-easy-apply-next-button="" type="button">...</button> is not clickable at point (954, 271). Other element would receive the click: <div class="search-typeahead-v2__hit search-typeahead-v2__hit--autocomplete" data-test-single-typeahead-entity-form-search-result="true">...</div>
  (Session info: chrome=128.0.6613.120)
Stacktrace:
        GetHandleVerifier [0x01078213+26163]
        (No symbol) [0x01009CC4]
        (No symbol) [0x00F024C3]
        (No symbol) [0x00F4D357]
        (No symbol) [0x00F4B759]
        (No symbol) [0x00F4964B]
        (No symbol) [0x00F48C2F]
        (No symbol) [0x00F3D9AF]
        (No symbol) [0x00F6ACBC]
        (No symbol) [0x00F3D445]
        (No symbol) [0x00F6AF54]
        (No symbol) [0x00F84661]
        (No symbol) [0x00F6AA56]
        (No symbol) [0x00F3BE89]
        (No symbol) [0x00F3C8CD]
        GetHandleVerifier [0x0134D313+2996019]
        GetHandleVerifier [0x013A1B89+3342249]
        GetHandleVerifier [0x01107AEF+614159]
        GetHandleVerifier [0x0110F17C+644508]
        (No symbol) [0x010127FD]
        (No symbol) [0x0100F6F8]
        (No symbol) [0x0100F895]
        (No symbol) [0x01001C16]
        BaseThreadInitThunk [0x757AFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x779780CE+286]
        RtlGetAppContainerNamedObjectPath [0x7797809E+238]

**Comment by 0HisRoyalMajesty0** [comment]
I am facing the exact same situation.
The bot encounters "Next" button and instead closes the application without saving it. Applications which are highly relevant as mentioned by @azjz92 
I would like to mention that I am using this for applying to "finance" roles and they all have further questions like years of experience in a specific field.
I would be really grateful if this issue could be resolved. Thank you so much!

**Comment by zirghamilyas** [comment]
Did you guys pay for the OpenAI API? 
If not, then this error occurs because of insufficient balance.

**Comment by 0HisRoyalMajesty0** [comment]
Apologies! I’m new to this all. How much is sufficient balance? I have access to ChatGPT4o.
________________________________

**Comment by 0HisRoyalMajesty0** [comment]
Thank you for your help!
After adding credit to OpenAI API, I was able to proceed further.
I would like to point out that, it still failed when using AI generated CV. However, when I used my own CV i was able to apply job.
________________________________

**Comment by feder-cr** [comment]
@baseadinho join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
