### ISSUE TITLE
Bug when encountering a dropdown Location/City Field

### ISSUE THREAD

**Issue by Younes43** [feder-cr/linkedIn_auto_jobs_applier_with_AI#282]
Whenever there is a location or city field, the bot is always unable to fill it, because he considers it as a textual field while in reality it is a dropdown.
This always results in exiting the application and moving to the next one

How It behave: 
![Screenshot 2024-09-05 022446](https://github.com/user-attachments/assets/b152548e-3cca-4017-9986-ee1e74a899cb)

How It should behave : it should select the first option of the dropdown, after typing the city
![Screenshot 2024-09-05 022459](https://github.com/user-attachments/assets/9539c5e4-2686-4ace-9223-56779e9ae739)

**Comment by mclacore** [comment]
I can confirm this bug. This is the output in the console I'm seeing:
```
Starting Chrome browser to log in to LinkedIn.
Navigating to the LinkedIn login page...
User is already logged in.
Starting the search for Junior platform engineer in United States.
Going to job page 0
Starting the application process for this page...
Traceback (most recent call last):
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 61, in job_apply
    self._fill_application_form(job)
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 126, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 139, in _next_or_submit
    next_button.click()
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-label="Continue to next step" id="ember500" class="artdeco-button artdeco-button--2 artdeco-button--primary ember-view" data-easy-apply-next-button="" type="button">...</button> is not clickable at point (999, 335). Other element would receive the click: <div class="search-typeahead-v2__hit search-typeahead-v2__hit--autocomplete" data-test-single-typeahead-entity-form-search-result="true">...</div>
  (Session info: chrome=128.0.6613.119)
Stacktrace:
0   chromedriver                        0x000000010460b998 cxxbridge1$str$ptr + 1887096
1   chromedriver                        0x0000000104603e00 cxxbridge1$str$ptr + 1855456
2   chromedriver                        0x0000000104208be0 cxxbridge1$string$len + 89508
3   chromedriver                        0x00000001042526fc cxxbridge1$string$len + 391360
4   chromedriver                        0x0000000104250d28 cxxbridge1$string$len + 384748
5   chromedriver                        0x000000010424ef54 cxxbridge1$string$len + 377112
6   chromedriver                        0x000000010424e4a0 cxxbridge1$string$len + 374372
7   chromedriver                        0x0000000104243930 cxxbridge1$string$len + 330484
8   chromedriver                        0x00000001042433c0 cxxbridge1$string$len + 329092
9   chromedriver                        0x00000001042864a4 cxxbridge1$string$len + 603752
10  chromedriver                        0x0000000104241a08 cxxbridge1$string$len + 322508
11  chromedriver                        0x000000010424266c cxxbridge1$string$len + 325680
12  chromedriver                        0x00000001045d2058 cxxbridge1$str$ptr + 1651256
13  chromedriver                        0x00000001045d698c cxxbridge1$str$ptr + 1669996
14  chromedriver                        0x00000001045b71ec cxxbridge1$str$ptr + 1541068
15  chromedriver                        0x00000001045d725c cxxbridge1$str$ptr + 1672252
16  chromedriver                        0x00000001045a8800 cxxbridge1$str$ptr + 1481184
17  chromedriver                        0x00000001045f50f8 cxxbridge1$str$ptr + 1794776
18  chromedriver                        0x00000001045f5274 cxxbridge1$str$ptr + 1795156
19  chromedriver                        0x0000000104603a9c cxxbridge1$str$ptr + 1854588
20  libsystem_pthread.dylib             0x0000000190cfdf94 _pthread_start + 136
21  libsystem_pthread.dylib             0x0000000190cf8d34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_job_manager.py", line 126, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 65, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception:
Traceback:
Traceback (most recent call last):
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 61, in job_apply
    self._fill_application_form(job)
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 126, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 139, in _next_or_submit
    next_button.click()
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/Users/mclacore/personal/linkedIn_auto_jobs_applier_with_AI/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-label="Continue to next step" id="ember500" class="artdeco-button artdeco-button--2 artdeco-button--primary ember-view" data-easy-apply-next-button="" type="button">...</button> is not clickable at point (999, 335). Other element would receive the click: <div class="search-typeahead-v2__hit search-typeahead-v2__hit--autocomplete" data-test-single-typeahead-entity-form-search-result="true">...</div>
  (Session info: chrome=128.0.6613.119)
Stacktrace:
0   chromedriver                        0x000000010460b998 cxxbridge1$str$ptr + 1887096
1   chromedriver                        0x0000000104603e00 cxxbridge1$str$ptr + 1855456
2   chromedriver                        0x0000000104208be0 cxxbridge1$string$len + 89508
3   chromedriver                        0x00000001042526fc cxxbridge1$string$len + 391360
4   chromedriver                        0x0000000104250d28 cxxbridge1$string$len + 384748
5   chromedriver                        0x000000010424ef54 cxxbridge1$string$len + 377112
6   chromedriver                        0x000000010424e4a0 cxxbridge1$string$len + 374372
7   chromedriver                        0x0000000104243930 cxxbridge1$string$len + 330484
8   chromedriver                        0x00000001042433c0 cxxbridge1$string$len + 329092
9   chromedriver                        0x00000001042864a4 cxxbridge1$string$len + 603752
10  chromedriver                        0x0000000104241a08 cxxbridge1$string$len + 322508
11  chromedriver                        0x000000010424266c cxxbridge1$string$len + 325680
12  chromedriver                        0x00000001045d2058 cxxbridge1$str$ptr + 1651256
13  chromedriver                        0x00000001045d698c cxxbridge1$str$ptr + 1669996
14  chromedriver                        0x00000001045b71ec cxxbridge1$str$ptr + 1541068
15  chromedriver                        0x00000001045d725c cxxbridge1$str$ptr + 1672252
16  chromedriver                        0x00000001045a8800 cxxbridge1$str$ptr + 1481184
17  chromedriver                        0x00000001045f50f8 cxxbridge1$str$ptr + 1794776
18  chromedriver                        0x00000001045f5274 cxxbridge1$str$ptr + 1795156
19  chromedriver                        0x0000000104603a9c cxxbridge1$str$ptr + 1854588
20  libsystem_pthread.dylib             0x0000000190cfdf94 _pthread_start + 136
21  libsystem_pthread.dylib             0x0000000190cf8d34 thread_start + 8
```

**Comment by baseadinho** [comment]
+1 here

**Comment by queukat** [comment]
fixed in new commits on v3 branch

**Comment by Younes43** [comment]
> fixed in new commits on v3 branch

Resolved I can confirm!
