### ISSUE TITLE
Failed to apply to job! Original exception

### ISSUE THREAD

**Issue by Necro-Coder** [feder-cr/linkedIn_auto_jobs_applier_with_AI#297]
Traceback (most recent call last):
  File "C:\Users\Practicas\Downloads\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_job_manager.py", line 126, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File "C:\Users\Practicas\Downloads\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 65, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception:
Traceback:
Traceback (most recent call last):
  File "C:\Users\Practicas\Downloads\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 55, in job_apply
    easy_apply_button = self._find_easy_apply_button()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Practicas\Downloads\LinkedIn_AIHawk_automatic_job_application\src\linkedIn_easy_applier.py", line 71, in _find_easy_apply_button
    buttons = WebDriverWait(self.driver, 10).until(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Practicas\Downloads\LinkedIn_AIHawk_automatic_job_application\venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by queukat** [comment]
can't find easy_apply_button on site

I made a few fixes in new commit, so you can try to update from v3 branch

**Comment by feder-cr** [comment]
@queukat ask for PR!

**Comment by queukat** [comment]
@feder-cr I probably put it wrong, in the comments it was meant that the changes were committed and the PR had already passed, so I just indicated "v3" without a specific link, implying that it was necessary to update from the main repository
