### ISSUE TITLE
clicked on easy apply but did not click next and moving to next application without completing the current applicatoin

### ISSUE THREAD

**Issue by Vinaynaidu1826** [feder-cr/linkedIn_auto_jobs_applier_with_AI#301]
Traceback (most recent call last):
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_easy_applier.py", line 60, in job_apply
    self.gpt_answerer.set_job(job)
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\src\gpt.py", line 147, in set_job
    self.job.set_summarize_job_description(self.summarize_job_description(self.job.description))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\src\gpt.py", line 158, in summarize_job_description
    output = chain.invoke({"text": text})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_core\runnables\base.py", line 2878, in invoke
    input = context.run(step.invoke, input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_core\runnables\base.py", line 4474, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_core\runnables\base.py", line 1785, in _call_with_config
    context.run(
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_core\runnables\config.py", line 398, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_core\runnables\base.py", line 4330, in _invoke
    output = call_func_with_variable_args(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_core\runnables\config.py", line 398, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\src\gpt.py", line 86, in __call__
    reply = self.llm(messages)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_core\_api\deprecation.py", line 180, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_core\language_models\chat_models.py", line 1016, in __call__
    generation = self.generate(
                 ^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_core\language_models\chat_models.py", line 634, in generate
    raise e
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_core\language_models\chat_models.py", line 624, in generate
    self._generate_with_cache(
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_core\language_models\chat_models.py", line 846, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\langchain_openai\chat_models\base.py", line 658, in _generate
    response = self.client.create(**payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\openai\resources\chat\completions.py", line 668, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\openai\_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\openai\_base_client.py", line 937, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\virtual\Lib\site-packages\openai\_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.PermissionDeniedError: Error code: 403 - {'error': {'message': 'Project `proj_r3T0Xu8I6cXZIusl0Wq8ey0U` does not have access to model `gpt-4o-mini`', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_job_manager.py", line 126, in apply_jobs        
    self.easy_applier_component.job_apply(job)
  File "C:\Users\vinay\OneDrive\Documents\New folder (3)\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_easy_applier.py", line 65, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception:
Traceback:

**Comment by queukat** [comment]
openai.PermissionDeniedError: Error code: 403 - {'error': {'message': 'Project proj_r3T0Xu8I6cXZIusl0Wq8ey0U does not have access to model gpt-4o-mini', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

check your models at openai

you supposed to choose the model you use or don't select any model (at openai)

**Comment by feder-cr** [comment]
@Vinaynaidu1826 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
