### ISSUE TITLE
error on pip install

### ISSUE THREAD

**Issue by ralyodio** [feder-cr/linkedIn_auto_jobs_applier_with_AI#65]
```
$ pip install -r requirements.txt
Collecting git+https://github.com/feder-cr/lib_resume_builder_AIHawk.git (from -r requirements.txt (line 14))
  Cloning https://github.com/feder-cr/lib_resume_builder_AIHawk.git to /tmp/pip-req-build-hg_e4zhr
  Running command git clone --filter=blob:none --quiet https://github.com/feder-cr/lib_resume_builder_AIHawk.git /tmp/pip-req-build-hg_e4zhr
  Resolved https://github.com/feder-cr/lib_resume_builder_AIHawk.git to commit 85084f925ae9043fb14dfa8d7c7ee8e21399afb1
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/ettinger/src/tmp/LinkedIn_AIHawk_automatic_job_application/myenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ettinger/src/tmp/LinkedIn_AIHawk_automatic_job_application/myenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ettinger/src/tmp/LinkedIn_AIHawk_automatic_job_application/myenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-adk4iqso/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-adk4iqso/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-adk4iqso/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 502, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-adk4iqso/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
````

**Comment by dmartin4820** [comment]
The error looks similar to one that I resolved locally. Basically, I noticed that the README.md file in the corresponding repo was saved in lowercase letters (e.g. readme.md). Renaming readme.md -> README.md got me past that point.

**Comment by ralyodio** [comment]
its already `README.md` for me

**Comment by dmartin4820** [comment]
It looks like the install is trying to pull from 

```Collecting git+https://github.com/feder-cr/lib_resume_builder_AIHawk.git (from -r requirements.txt (line 14))```

That repo contains "readme.md". In my case, 

- I cloned down the repo manually, installed it into my environment (I'm using conda), 
- Did a pip install -r requirements in linkedIn_auto_jobs_applier_with_AI

It did not have any issues installing after that. I should say that doing this goes completely off path though, so I'm not sure what other issues or side effects it may cause. Can't be responsible for that :P.

**Comment by ralyodio** [comment]
oh i have write access to that repo. I'll fix it.

**Comment by feder-cr** [comment]
@ralyodio @dmartin4820  file renamed, now lib is ok?

**Comment by dmartin4820** [comment]
@feder-cr Looks good to me. Here's the steps I took to check it:

1. Pull changes to linkedIn_auto_jobs_applier_with_AI from remote main into my local
2. run ```cd /path/to/linkedIn_auto_jobs_applier_with_AI && pip install -r requirements.txt```

I was able to run that without issue now using the unmodified requirements.txt file.
