### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by us** [feder-cr/linkedIn_auto_jobs_applier_with_AI#7]
python main.py
Traceback (most recent call last):
  File "/Users/syny/kafamagore/LinkedIn_AIHawk_automatic_job_application/main.py", line 120, in <module>
    class FileManager:
  File "/Users/syny/kafamagore/LinkedIn_AIHawk_automatic_job_application/main.py", line 151, in FileManager
    def file_paths_to_dict(resume_file: Path | None, plain_text_resume_file: Path) -> dict:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

python3.9

**Comment by us** [comment]
solution find! python3.9 is not supported | , so please specify in readme please! supported for 3.10 and +
