### ISSUE TITLE
Issue with Element Locator: NoSuchElementException for 'jobs-easy-apply-content

### ISSUE THREAD

**Issue by Zabih-khan** [feder-cr/linkedIn_auto_jobs_applier_with_AI#79]
I getting this error please fix it.

Traceback (most recent call last):
  File "E:\NLP\Linkedin project\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_easy_applier.py", line 63, in job_apply
    self._fill_application_form(job)
  File "E:\NLP\Linkedin project\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_easy_applier.py", line 129, in _fill_application_form
    self.fill_up(job)
  File "E:\NLP\Linkedin project\linkedIn_auto_jobs_applier_with_AI\src\linkedIn_easy_applier.py", line 170, in fill_up
    easy_apply_content = self.driver.find_element(By.CLASS_NAME, 'jobs-easy-apply-content')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\khan\anaconda3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\khan\anaconda3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute    
    self.error_handler.check_response(response)
  File "C:\Users\khan\anaconda3\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-easy-apply-content"}
  (Session info: chrome=128.0.6613.84)

**Comment by feder-cr** [comment]
@Zabih-khan restart the bot

**Comment by feder-cr** [comment]
@Zabih-khan  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by Zabih-khan** [comment]
Okay

**Comment by yasinlachiny** [comment]
Same issue and no answer in the telegram
